name: Web client CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.3.1]
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install & lint
      run: |
        cd web/client
        yarn install --immutable
        yarn lint
    - name: Build
      run: |
        cd web/client
        yarn build
    - name: Test
      run: |
        cd web/client
        yarn test:unit
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     file: ./client/coverage/coverage-final.json
    #     flags: unittests
    #     name: codecov-umbrella
